apiVersion: apps/v1
kind: Deployment
metadata:
  name: __APP_NAME__
  labels:
    app: __APP_NAME__
spec:
  replicas: 2
  selector:
    matchLabels:
      app: __APP_NAME__
  template:
    metadata:
      labels:
        app: __APP_NAME__
    spec:
      containers:
        - name: __APP_NAME__
          image: __FULL_IMAGE__
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: __APP_NAME__
  labels:
    app: __APP_NAME__
spec:
  selector:
    app: __APP_NAME__
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
