// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingSystemsMonitoring.DataModel.DbContext;

namespace TradingSystemsMonitoring.DataModel.Migrations.TradingDataDb
{
    [DbContext(typeof(TradingDataDbContext))]
    [Migration("20250321071611_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TradingSystemsMonitoring.DataModel.Entities.Trading.AccountClosedTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("ClosingPrice")
                        .HasColumnType("float");

                    b.Property<string>("FutCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("OpeningPrice")
                        .HasColumnType("float");

                    b.Property<byte>("Operation")
                        .HasColumnType("tinyint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<double>("ResultInCash")
                        .HasColumnType("float");

                    b.Property<double>("ResultInPercent")
                        .HasColumnType("float");

                    b.Property<double>("ResultInTicks")
                        .HasColumnType("float");

                    b.Property<string>("SystemId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("fk_SecurityId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("fk_SecurityId");

                    b.ToTable("AccountClosedTrades");
                });

            modelBuilder.Entity("TradingSystemsMonitoring.DataModel.Entities.Trading.Security", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exchange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Securities");
                });

            modelBuilder.Entity("TradingSystemsMonitoring.DataModel.Entities.Trading.AccountClosedTrade", b =>
                {
                    b.HasOne("TradingSystemsMonitoring.DataModel.Entities.Trading.Security", "Security")
                        .WithMany("AccountClosedTrades")
                        .HasForeignKey("fk_SecurityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Security");
                });

            modelBuilder.Entity("TradingSystemsMonitoring.DataModel.Entities.Trading.Security", b =>
                {
                    b.Navigation("AccountClosedTrades");
                });
#pragma warning restore 612, 618
        }
    }
}
