<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Trading\**" />
    <EmbeddedResource Remove="Trading\**" />
    <None Remove="Trading\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TradingSystemsMonitoring.DataModel\TradingSystemsMonitoring.DataModel.csproj" />
  </ItemGroup>

</Project>
