<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Trading\**" />
    <EmbeddedResource Remove="Trading\**" />
    <None Remove="Trading\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="StackExchange.Redis" Version="2.11.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TradingSystemsMonitoring.DataModel\TradingSystemsMonitoring.DataModel.csproj" />
  </ItemGroup>

</Project>
